### ISSUE TITLE
[功能请求] 支持插件更新

### ISSUE THREAD

**Issue by steve02081504** [Mon1-innovation/MAS-Simplified-Chinese-Patch#2]
有一个submod可以更新其他submod，链接在https://github.com/Booplicate/MAS-Submods-SubmodUpdaterPlugin/tree/master
很多submod都支持它，我想或许汉化补丁也可以这样做来方便更新？

**Comment by PencilMario** [comment]
想了一下，估计是不行，这个库设计的时候就没考虑到更新器
为了保持和安装器的兼容，~~以及偷懒~~，咕了
设计一个更新的子模组应该不难，游戏启动时两个补丁可以替换掉
