### ISSUE TITLE
[功能请求] 囊括其他submod的汉化？

### ISSUE THREAD

**Issue by steve02081504** [Mon1-innovation/MAS-Simplified-Chinese-Patch#3]
mas有很多submod来扩展功能，有计划扩展汉化范畴让submod也能被本地化吗？
![图片](https://github.com/Mon1-innovation/MAS-Simplified-Chinese-Patch/assets/31927825/6a4b087a-0d81-42b6-b057-1b58278df9bb)

我不清楚实现起来会不会困难所以如果难以做到的话关掉这个issue就好

**Comment by PencilMario** [comment]
这只是MAS本体的汉化补丁，而且不同子模组的汉化方式也不一样，不能说就十分方便的兼容
而且多这部分内容也要增加额外维护的部分，我是没什么动力的，不过也可以单独用一个子模组去做汉化
另外，你图里这几个应该也有汉化版本
